version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: twitter_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: twitter_clone
      MYSQL_USER: twitter_user
      MYSQL_PASSWORD: twitter_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - twitter_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Node.js Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: twitter_backend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: twitter_clone
      DB_USER: twitter_user
      DB_PASSWORD: twitter_password
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 6969
    ports:
      - "6969:6969"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - twitter_network

  # WebSocket Server - DISABLED
  # websocket:
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile.websocket
  #   container_name: twitter_websocket
  #   restart: unless-stopped
  #   environment:
  #     NODE_ENV: development
  #     WS_PORT: 8080
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - twitter_network

  # React Frontend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: twitter_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:6969
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - twitter_network

  # phpMyAdmin - Web interface for MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: twitter_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: twitter_user
      PMA_PASSWORD: twitter_password
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - twitter_network

volumes:
  mysql_data:

networks:
  twitter_network:
    driver: bridge